/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurantepresentacion_262757_262804_247427;

import com.mycompany.restaurantedominio_262757_247427_262804.Ingrediente;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author BALAMRUSH
 */
public class BusquedaIngredienteFORM extends javax.swing.JFrame {

    private ControlForms control;
    
    public BusquedaIngredienteFORM(ControlForms control) {
        this.control = control;
        initComponents();
        inicializarComboBox();
        java.awt.EventQueue.invokeLater(() -> {
            cargarTodosLosIngredientes();
        }); 
    }
    
    /**
     * Aqui cargamos todos los ingredientes, como esta definido por si esta
     * vacio algun campo mande a llamar a todo lo que hay en la base de datos
     * mandamos los parametros vacios
     */
    private void cargarTodosLosIngredientes() {
        control.buscarIngredientes("","");
    }
    
    /**
     * inicializamos el comboBox con las posibles tipos de filtros
     */
    private void inicializarComboBox() {
        controlFiltroBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Nombre", "Unidad de Medida"}
        ));
    }
    
    /**
     * mostramos los resultados de los ingredientes para ponerlos en tabla
     * @param ingrediente 
     */
    public void mostrarResultados(List<Ingrediente> ingrediente) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaIngredientes.getModel();
        modelo.setRowCount(0);

        for (Ingrediente i : ingrediente) {
            modelo.addRow(new Object[]{
                i.getIdIngrediente(),
                i.getNombreIngrediente(),
                i.getStockIngrediente(),
                i.getUnidadMedida(),
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        textFieldBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIngredientes = new javax.swing.JTable();
        controlFiltroBusqueda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        botonModificarStock = new javax.swing.JButton();
        buttonEliminarIngrediente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Búsqueda Ingrediente");
        setResizable(false);
        setSize(new java.awt.Dimension(595, 552));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(595, 552));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Búsqueda Ingrediente");

        botonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonBuscar.setLabel("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        tablaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "STOCK", "UNIDAD DE MEDIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaIngredientes.getTableHeader().setResizingAllowed(false);
        tablaIngredientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaIngredientes);

        jLabel2.setText("Filltro Búsqueda ");

        botonAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(153, 153, 153));
        botonAtras.setText(">");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonModificarStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonModificarStock.setText("Modificar Stock");
        botonModificarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarStockActionPerformed(evt);
            }
        });

        buttonEliminarIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonEliminarIngrediente.setText("Eliminar Ingrediente");
        buttonEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAtras)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(controlFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(textFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(buttonEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonModificarStock))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(botonAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controlFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonEliminarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarStock, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        botonBuscar.getAccessibleContext().setAccessibleName("botonBuscar");
        textFieldBusqueda.getAccessibleContext().setAccessibleName("textFiielBusqueda");
        controlFiltroBusqueda.getAccessibleContext().setAccessibleName("comboFIltrosBusqueda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String texto = textFieldBusqueda.getText().trim();
        String tipoFiltro = (String) controlFiltroBusqueda.getSelectedItem();
        control.buscarIngredientes(texto, tipoFiltro);
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        volverAtras();
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * Le muestra al usuario la cantidad para sumar o restar pudiendo dar 
     * numeros negativos para restar, y así actualizar la cantidad
     * @param evt 
     */
    private void botonModificarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarStockActionPerformed
        int fila = tablaIngredientes.getSelectedRow();
        if(fila < 0){
            return;
        }
        Long id = (Long) tablaIngredientes.getValueAt(fila, 0);
        String nombre = tablaIngredientes.getValueAt(fila, 1).toString();
        Double stockActual = (Double) tablaIngredientes.getValueAt(fila, 2);
        
        String input = javax.swing.JOptionPane.showInputDialog(this,"Ingresar la cantidad que quiera suma (+) o restar (-) del stock.");
        if(input != null && !input.trim().isEmpty()){
            control.actualizarStockIngrediente(id, input.trim());
        }
                
    }//GEN-LAST:event_botonModificarStockActionPerformed
    
    /**
     * elimina el ingrediente seleccionado por el usuario para poder eliminarlo
     * buscandolo por el id en el metodo eliminar ingrediente
     * @param evt 
     */
    private void buttonEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarIngredienteActionPerformed
        int fila = tablaIngredientes.getSelectedRow();
        if(fila < 0){
            JOptionPane.showMessageDialog(this, "Selecciona un ingrediente de la tabla antes de hacer alguna acción.", "Alerta", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Long id = (Long) tablaIngredientes.getValueAt(fila, 0);
        String nombre = tablaIngredientes.getValueAt(fila, 1).toString();
        
        int confirmarEliminacion = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar este ingrediente?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if(confirmarEliminacion == JOptionPane.YES_OPTION){
            control.eliminarIngrediente(id);
            cargarTodosLosIngredientes();
        }
        
    }//GEN-LAST:event_buttonEliminarIngredienteActionPerformed

     public void volverAtras() {
        control.navegarMenuIngredientes();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonModificarStock;
    private javax.swing.JButton buttonEliminarIngrediente;
    private javax.swing.JComboBox<String> controlFiltroBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaIngredientes;
    private javax.swing.JTextField textFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
